development:
  adapter: mysql2
  database: aw_dev
  username: root
  password: root

test:
  adapter: mysql2
  database: aw_testing
  username: root
  password: root

production:
  adapter: mysql2
  database: aw_prod
  username: root
  password: root
